# Generated by Django 5.1 on 2024-08-12 12:33

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
           
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+11234567890', max_length=128, region=None),
            preserve_default=False,
        ),
        #migrations.AlterField(
            #model_name='profile',
            #name='country',
            #field=django_countries.fields.CountryField(max_length=50),
        #),
    ]
