# Generated by Django 5.1 on 2024-08-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_profile_country_profile_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=2),
        ),
    ]
