# Generated by Django 5.1 on 2024-08-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=100),
        ),
    ]
